name: 'chronic_conditions'
version: '0.1.0'
config-version: 2

profile: syntegra_snowflake       # configuration required (your profile to connect dbt to your data warehouse)

vars:
    source_database: tuva         # configuration required (name of the database where data feeding this project is stored - tuva by default)
    source_schema: core           # configuration required (name of the schema where data feeding this project is stored - core by default)
    source_name: core             # configuration required (name of describing the dataset feeding this project - typically matches schema name)

    encounter: "{{ source(var('source_name'),'encounter') }}"
    condition: "{{ source(var('source_name'),'condition') }}"
    procedure: "{{ source(var('source_name'),'procedure') }}"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  chronic_conditions:
    +database: tuva
    +schema: chronic_conditions

seeds:
  chronic_conditions:
    +database: tuva
    +schema: terminology
    +tags: terminolgoy