name: 'cms_chronic_conditions'
version: '0.1.5'
config-version: 2
profile: 'default'


vars:
    prescription: |
        {% if var('cms_chronic_conditions_prescription_override',none) is not none %}{{var('cms_chronic_conditions_prescription_override')}}
        {%- elif var('core_prescription_override',none) is not none %}{{var('core_prescription_override')}}
        {%- else %}{{ref('claims_preprocessing__prescription')}}
        {% endif %}
    encounter: |
        {% if var('cms_chronic_conditions_encounter_override',none) is not none %}{{var('cms_chronic_conditions_encounter_override')}}
        {%- elif var('core_encounter_override',none) is not none %}{{var('core_encounter_override')}}
        {%- else %}{{ref('claims_preprocessing__encounter')}}
        {% endif %}
    condition: |
        {% if var('cms_chronic_conditions_condition_override',none) is not none %}{{var('cms_chronic_conditions_condition_override')}}
        {%- elif var('core_condition_override',none) is not none %}{{var('core_condition_override')}}
        {%- else %}{{ref('claims_preprocessing__condition')}}
        {% endif %}
    procedure: |
        {% if var('cms_chronic_conditions_condition_override',none) is not none %}{{var('cms_chronic_conditions_condition_override')}}
        {%- elif var('core_condition_override',none) is not none %}{{var('core_condition_override')}}
        {%- else %}{{ref('claims_preprocessing__condition')}}
        {% endif %}  
  


model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"


