name: 'chronic_conditions'
version: '0.1.1'
config-version: 2


profile: 'default'

vars:

### optional overrides for input data, only for integration_test or use as a project
#  chronic_conditions_input_database: tuva                 # optional: name of the database where sources feeding this prorject are stored
#                                                          # default: tuva
#
#  chronic_conditions_input_schema: test_core              # optional: name of the schema where sources feeding this project are stored
#                                                          # default: core



## optional output config option 1 (all tuva packages)
#  tuva_database: tuva                                     # optional: name of the database where tables from this package will be written
#                                                          # default: tuva
#
#  tuva_schema_prefix: test                                # optional: name of the schema where tables from this package will be written
#                                                          # default: chronic_conditions


## optional output config option 2 (package specific config), overrides option 1
#  chronic_conditions_database: tuva                       # optional: name of the database where tables from this package will be written
#                                                          # default: tuva
#
#  chronic_conditions_schema: test_chronic_conditions      # optional: name of the schema where tables from this package will be written
#                                                          # default: chronic

  condition: "{% if project_name == 'chronic_conditions' %}{{ source('core','condition') }}{% else %}{{ ref('claims_preprocessing__condition') }}{% endif %}"
  encounter: "{% if project_name == 'chronic_conditions' %}{{ source('core','encounter') }}{% else %}{{ ref('claims_preprocessing__encounter') }}{% endif %}"
  prescription: "{% if project_name == 'chronic_conditions' %}{{ source('core','prescription') }}{% else %}{{ ref('claims_preprocessing__prescription') }}{% endif %}"
  procedure: "{% if project_name == 'chronic_conditions' %}{{ source('core','procedure') }}{% else %}{{ ref('claims_preprocessing__procedure') }}{% endif %}"



model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
  chronic_conditions:
    +materialized: table