name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 'default'



vars:

### output config option 1, applies to all tuva packages
  tuva_database: dev_user
  tuva_schema_prefix: test

### output config option 2, applies to chronic_conditions, overrides option 1
#  chronic_conditions_database: tuva
#  chronic_conditions_schema: test_chronic_conditions


### input config option 1, applies to all SmartMarts
#  core_condition_override: "{{ref('condition')}}"
#  core_patient_override:   "{{ref('prescription')}}"
#  core_encounter_override: "{{ref('encounter')}}"
#  core_procedure_override: "{{ref('procedure')}}"

## you can also point these to sources
#  core_condition_override: "{{source('core','condition')}}"
#  core_patient_override:   "{{source('core','prescription')}}"
#  core_encounter_override: "{{source('core','encounter')}}"
#  core_procedure_override: "{{source('core','procedure')}}"


### input config option 2, applies to chronic_conditions, overrides option 1
#  chronic_conditions_condition_override: "{{ref('condition')}}"
#  chronic_conditions_patient_override:   "{{ref('prescription')}}"
#  chronic_conditions_encounter_override: "{{ref('encounter')}}"
#  chronic_conditions_procedure_override: "{{ref('procedure')}}"



### enabled/disabled configs
## applies to all packages
  tuva_packages_enabled: false

## applies to chronic_conditions only
  chronic_conditions_enabled: true
#  terminology enabled: false

dispatch:
  - macro_namespace: dbt
    search_order: [ 'chronic_conditions', 'dbt']


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral
#    +database: dev_user