name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 'default'



vars:

## optional output config option 1 (configs apply to all tuva packages)
#
#  tuva_database: tuva                                      # optional: name of the database where tables from this package will be written
#                                                           # default: tuva
#
#  tuva_schema_prefix: test                                 # optional: prefix (+_) that will be prerpended to all tuva package schema defaults
#                                                           # default schema: core (no prefix by default
#
#
#
## optional output config option 2 (package specific config), overrides option 1
#
#  chronic_conditions_database: tuva                        # optional: name of the database where tables from this package will be written
#                                                           # default: tuva
#
#  chronic_conditions_schema: test_chronic_conditions       # optional: name of the schema where tables from this package will be written
#                                                           # default: core
#







### optional overrides for input data, only for use as a project
#  chronic_conditions_input_database: tuva             # optional: name of the database where sources feeding this prorject are stored
#                                                      # default: tuva

#  chronic_conditions_input_schema: test_claims_input  # optional: name of the schema where sources feeding this project are stored
#                                                      # default: claims_input



model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral