name: 'chronic_conditions_input'
version: '1.0.0'
config-version: 2

profile: 'default'



vars:
#  tuva_packages_enabled: false
#  chronic_conditions_enabled: true
  chronic_conditions_condition_override: "{{ref('condition')}}"
  chronic_conditions_prescription_override:   "{{ref('prescription')}}"
  chronic_conditions_encounter_override: "{{ref('encounter')}}"
  chronic_conditions_procedure_override: "{{ref('procedure')}}"

dispatch:
  - macro_namespace: dbt
    search_order: [ 'chronic_conditions', 'dbt']

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["documents"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  chronic_conditions_input:
    +materialized: view